jobs:
  cleanup:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out code
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Cleanup
      run: "gh extension install actions/gh-actions-cache\n\nREPO=${{ github.repository\
        \ }}\nBRANCH=${{ github.ref }}\n\necho \"Fetching list of cache key\"\ncacheKeysForPR=$(gh\
        \ actions-cache list -R $REPO -B $BRANCH | cut -f 1 )\n\n## Setting this to\
        \ not fail the workflow while deleting cache keys. \nset +e\necho \"Deleting\
        \ caches...\"\nfor cacheKey in $cacheKeysForPR\ndo\n    gh actions-cache delete\
        \ $cacheKey -R $REPO -B $BRANCH --confirm\ndone\necho \"Done\"\n"
name: cleanup caches by a branch
on:
  repository_dispatch:
    types: trigger-ga___cache-cleanup.yaml
