concurrency:
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/v1'
    }}
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  MAVEN_OPTS: -Xmx4g
jobs:
  integration-test:
    name: Integration tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Disable Mono
      run: 'sudo killall mono

        sudo lsof -iTCP -n -P | sort -k1

        '
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - continue-on-error: true
      name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Setup Maven
      run: "mkdir -p ~/.m2\ncat <<EOF > ~/.m2/settings.xml\n<settings>\n  <servers>\n\
        \    <server>\n      <id>artifactory-snapshots</id>\n      <username>${ARTIFACTORY_USERNAME}</username>\n\
        \      <password>${ARTIFACTORY_PASSWORD}</password>\n    </server>\n    <server>\n\
        \      <id>artifactory-releases</id>\n      <username>${ARTIFACTORY_USERNAME}</username>\n\
        \      <password>${ARTIFACTORY_PASSWORD}</password>\n   </server>\n </servers>\n\
        </settings>\nEOF\n"
    - continue-on-error: true
      name: Install CCM
      run: 'python -m pip install --upgrade pip setuptools

        python -m pip install ccm

        ccm list

        '
    - continue-on-error: true
      name: Run Integration Tests
      run: 'cd coordinator/

        ./mvnw -B -ntp ${{ matrix.build-profile }} clean install -DskipTests

        ./mvnw -B -ntp -pl testing ${{ matrix.test-profile }} clean verify -DskipUnitTests

        '
    strategy:
      fail-fast: false
      matrix:
        backend:
        - cassandra-40
        - cassandra-311
        - dse-68
        include:
        - backend: cassandra-40
          build-profile: null
          test-profile: -P it-cassandra-4.0
        - backend: cassandra-311
          build-profile: null
          test-profile: -P it-cassandra-3.11
        - backend: dse-68
          build-profile: -P dse
          test-profile: -P dse -P it-dse-6.8
    timeout-minutes: 120
  unit-test:
    name: Coordinator unit tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - continue-on-error: true
      name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Setup Maven
      run: "mkdir -p ~/.m2\ncat <<EOF > ~/.m2/settings.xml\n<settings>\n  <servers>\n\
        \    <server>\n      <id>artifactory-snapshots</id>\n      <username>${ARTIFACTORY_USERNAME}</username>\n\
        \      <password>${ARTIFACTORY_PASSWORD}</password>\n    </server>\n    <server>\n\
        \      <id>artifactory-releases</id>\n      <username>${ARTIFACTORY_USERNAME}</username>\n\
        \      <password>${ARTIFACTORY_PASSWORD}</password>\n   </server>\n </servers>\n\
        </settings>\nEOF\n"
    - continue-on-error: true
      name: Install CCM
      run: 'python -m pip install --upgrade pip setuptools

        python -m pip install ccm

        ccm list

        '
    - continue-on-error: true
      name: Run unit tests
      run: 'cd coordinator/

        ./mvnw -B -ntp clean test -P dse

        '
    timeout-minutes: 45
name: Coordinator Tests v2.1
on:
  repository_dispatch:
    types: trigger-ga___coordinator-test-v21.yml
